# Generated by Django 4.1.1 on 2022-10-21 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Número de Pedido'),
        ),
    ]
