# Generated by Django 4.1.1 on 2022-10-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto'},
        ),
        migrations.AlterField(
            model_name='unitmeasurecategory',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
